### ISSUE TITLE
Suggestion: keep boto connection open for persistent

### ISSUE THREAD

**Issue by DeviaVir** [pebble/cloudwatch-mon-scripts-python#5]
From https://github.com/pebble/cloudwatch-mon-scripts-python/pull/3

> Might be able to reclaim some overhead by keeping the boto.ec2.cloudwatch.connect_to_region client around for every request (instead of re-creating/fresh connection every run).

**Comment by thepwagner** [comment]
Could also be insane (i.e. AWS won't KeepAlive transactions >60s).
